### PR TITLE
Check for non coercible data in source #3

### LINKED ISSUE #3: HbaseScheme assumes utf-8 encoded blob
Is there a particular reason for doing this ?
https://github.com/Cascading/cascading.hbase/blob/2.2/src/main/java/cascading/hbase/HBaseScheme.java#L141

This implies that i cannot have HBaseTap working on anything other than utf-8 encoded data. Is there a way to have raw bytes or a custom de/serialization for the tap?

### PR DESCRIPTION
**Pull request by kul**
Fixes #3.

### CODE REVIEW

**Comment by kul** [comment]
the 'test' classified dependency is not found for cascading-hadoop on any of the repos in build file. How are you testing this?

**Comment by fs111** [comment]
`gradle clean build` works for me. What kind of error do you get?

**Comment by kul** [comment]
no matter what i do i keep getting 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':testCompile'.
> Could not download artifact 'cascading:cascading-hadoop:2.2.0:cascading-hadoop-tests.jar'
   > Artifact 'cascading:cascading-hadoop:2.2.0:cascading-hadoop-tests.jar' not found.
```

**pr is untested.**

**Comment by fs111** [comment]
Can you run `gradle -i -s clean build` and post the output here? 

Also: Which gralde and java version do you have?

**Comment by kul** [comment]
java version "1.7.0_51"
Gradle 1.11

https://www.refheap.com/61397

**Comment by fs111** [comment]
The jar is on conjars: http://conjars.org/repo/cascading/cascading-hadoop/2.2.0/cascading-hadoop-2.2.0-tests.jar Can you reach that from your end?

**Comment by kul** [comment]
Yes, i can download that, blowing up  the ~/.gradle/cache right now. Hope works this time.

**EDIT** Ok I give up same error even after removing the whole cache, would you mind testing the PR?

**Comment by kul** [comment]
@fs111 seems like there was problem with maven and gradle caches after all. I removed the corresponding deps in maven cache and it worked. All test cases are passing.

It seems if gradle doesnt find the *-tests jar in local maven repo but the normal dep it declares that no such dep exists. May be this is a gradle bug.
But i also had to include the zookeeper dep in the build file.

Thanks

**Comment by kul** [comment]
@fs111 any comments on the pr?

**Comment by fs111** [comment]
I wonder if it would not make more sense, if we expose a setting in the constructor to set the encoding in the constructor and have a sane fallback, of none was given.

**Comment by kul** [comment]
@fs111 is  returing null when type is not coercible sensible?
This PR just returns raw bytes if the type is not coercible and IMO will be required even if you add custom encodings later on to tap.
Regards

**Pull request closed without merging**
